### ISSUE TITLE
Could you provide the datasets?

### ISSUE THREAD

**Issue by lzxlin** [AilabUdineGit/ontology-pretraining-code#1]
Hello,
I had the honor to read your paper “Generalizing over Long Tail Concepts for Medical Term Normalization”, and I think the idea is meaningful. Thanks for the code you provided. Could you provide me with the datasets? Thank you very much.

**Comment by simonescaboro** [comment]
Hi, thank you for your interest in our paper. In the next few days, we will update the README file with the information on where the datasets can be downloaded because we cannot share them directly.
